name: A
run-name: A

on:
  push:
    branches:
      - main

jobs:
  development:
    runs-on: ubuntu-latest
    name: Deploy Development
    environment: Development
    steps:
      - name: Checkout
        run: |-
          echo Deployment

  staging:
    runs-on: ubuntu-latest
    name: Deploy Staging
    environment: Staging
    needs: development
    steps:
      - name: Checkout
        run: |-
          echo Staging
